[package]
name = "greedyman"
version = "0.1.0"
authors = ["Edward Bennigsen <edward.bennigsen@protonmail.com>"]

[dependencies]
nineman = { git = "https://github.com/UsAndRufus/nineman", tag= "v0.3.0" }
rand = "0.4.1"
